export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const CHOSEN_ARTICLE = 'CHOSEN_ARTICLE';
export const SEARCH_INPUT = 'SEARCH_INPUT';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const CLICKED_SECTION = 'CLICKED_SECTION';
